// Mon Imagier — données
// Chaque item : [id, article, nom]
window.IMAGIER = {
  themes: [
    {
      id: 'ferme',
      title: 'À la ferme',
      cover: 'vache',
      items: [
        ['chat', 'le', 'chat'],
        ['chien', 'le', 'chien'],
        ['vache', 'la', 'vache'],
        ['cochon', 'le', 'cochon'],
        ['mouton', 'le', 'mouton'],
        ['chevre', 'la', 'chèvre'],
        ['cheval', 'le', 'cheval'],
        ['ane', "l'", 'âne'],
        ['poule', 'la', 'poule'],
        ['coq', 'le', 'coq'],
        ['poussin', 'le', 'poussin'],
        ['canard', 'le', 'canard'],
        ['lapin', 'le', 'lapin'],
        ['souris', 'la', 'souris'],
        ['oie', "l'", 'oie'],
        ['dindon', 'le', 'dindon'],
      ],
    },
    {
      id: 'sauvages',
      title: 'Les animaux sauvages',
      cover: 'lion',
      items: [
        ['lion', 'le', 'lion'],
        ['tigre', 'le', 'tigre'],
        ['elephant', "l'", 'éléphant'],
        ['girafe', 'la', 'girafe'],
        ['zebre', 'le', 'zèbre'],
        ['singe', 'le', 'singe'],
        ['hippopotame', "l'", 'hippopotame'],
        ['rhinoceros', 'le', 'rhinocéros'],
        ['crocodile', 'le', 'crocodile'],
        ['serpent', 'le', 'serpent'],
        ['ours', "l'", 'ours'],
        ['panda', 'le', 'panda'],
        ['koala', 'le', 'koala'],
        ['kangourou', 'le', 'kangourou'],
        ['renard', 'le', 'renard'],
        ['loup', 'le', 'loup'],
        ['cerf', 'le', 'cerf'],
        ['ecureuil', "l'", 'écureuil'],
        ['herisson', 'le', 'hérisson'],
        ['pingouin', 'le', 'pingouin'],
        ['tortue', 'la', 'tortue'],
        ['paresseux', 'le', 'paresseux'],
        ['flamant-rose', 'le', 'flamant rose'],
        ['chameau', 'le', 'chameau'],
      ],
    },
    {
      id: 'mer',
      title: 'Sous la mer',
      cover: 'pieuvre',
      items: [
        ['poisson', 'le', 'poisson'],
        ['baleine', 'la', 'baleine'],
        ['dauphin', 'le', 'dauphin'],
        ['requin', 'le', 'requin'],
        ['pieuvre', 'la', 'pieuvre'],
        ['crabe', 'le', 'crabe'],
        ['etoile-de-mer', "l'", 'étoile de mer'],
        ['hippocampe', "l'", 'hippocampe'],
        ['meduse', 'la', 'méduse'],
        ['phoque', 'le', 'phoque'],
        ['coquillage', 'le', 'coquillage'],
        ['homard', 'le', 'homard'],
      ],
    },
    {
      id: 'betes',
      title: 'Les petites bêtes',
      cover: 'coccinelle',
      items: [
        ['abeille', "l'", 'abeille'],
        ['coccinelle', 'la', 'coccinelle'],
        ['papillon', 'le', 'papillon'],
        ['chenille', 'la', 'chenille'],
        ['escargot', "l'", 'escargot'],
        ['fourmi', 'la', 'fourmi'],
        ['araignee', "l'", 'araignée'],
        ['libellule', 'la', 'libellule'],
        ['sauterelle', 'la', 'sauterelle'],
        ['ver-de-terre', 'le', 'ver de terre'],
        ['mouche', 'la', 'mouche'],
        ['grenouille', 'la', 'grenouille'],
      ],
    },
    {
      id: 'oiseaux',
      title: 'Les oiseaux',
      cover: 'hibou',
      items: [
        ['oiseau', "l'", 'oiseau'],
        ['hibou', 'le', 'hibou'],
        ['perroquet', 'le', 'perroquet'],
        ['toucan', 'le', 'toucan'],
        ['cygne', 'le', 'cygne'],
        ['autruche', "l'", 'autruche'],
        ['paon', 'le', 'paon'],
        ['pelican', 'le', 'pélican'],
        ['colibri', 'le', 'colibri'],
        ['rouge-gorge', 'le', 'rouge-gorge'],
      ],
    },
    {
      id: 'fruits',
      title: 'Les fruits',
      cover: 'fraise',
      items: [
        ['pomme', 'la', 'pomme'],
        ['poire', 'la', 'poire'],
        ['banane', 'la', 'banane'],
        ['orange', "l'", 'orange'],
        ['fraise', 'la', 'fraise'],
        ['framboise', 'la', 'framboise'],
        ['cerise', 'la', 'cerise'],
        ['raisin', 'le', 'raisin'],
        ['peche', 'la', 'pêche'],
        ['abricot', "l'", 'abricot'],
        ['prune', 'la', 'prune'],
        ['citron', 'le', 'citron'],
        ['pasteque', 'la', 'pastèque'],
        ['melon', 'le', 'melon'],
        ['ananas', "l'", 'ananas'],
        ['mangue', 'la', 'mangue'],
        ['kiwi', 'le', 'kiwi'],
        ['noix-de-coco', 'la', 'noix de coco'],
        ['myrtille', 'la', 'myrtille'],
        ['figue', 'la', 'figue'],
      ],
    },
    {
      id: 'legumes',
      title: 'Les légumes',
      cover: 'carotte',
      items: [
        ['carotte', 'la', 'carotte'],
        ['tomate', 'la', 'tomate'],
        ['pomme-de-terre', 'la', 'pomme de terre'],
        ['courgette', 'la', 'courgette'],
        ['aubergine', "l'", 'aubergine'],
        ['poivron', 'le', 'poivron'],
        ['brocoli', 'le', 'brocoli'],
        ['chou-fleur', 'le', 'chou-fleur'],
        ['salade', 'la', 'salade'],
        ['concombre', 'le', 'concombre'],
        ['radis', 'le', 'radis'],
        ['mais', 'le', 'maïs'],
        ['petits-pois', 'les', 'petits pois'],
        ['oignon', "l'", 'oignon'],
        ['champignon', 'le', 'champignon'],
        ['citrouille', 'la', 'citrouille'],
        ['poireau', 'le', 'poireau'],
        ['betterave', 'la', 'betterave'],
      ],
    },
    {
      id: 'vehicules',
      title: 'Les véhicules',
      cover: 'fusee',
      items: [
        ['voiture', 'la', 'voiture'],
        ['camion', 'le', 'camion'],
        ['bus', 'le', 'bus'],
        ['velo', 'le', 'vélo'],
        ['moto', 'la', 'moto'],
        ['train', 'le', 'train'],
        ['avion', "l'", 'avion'],
        ['helicoptere', "l'", 'hélicoptère'],
        ['bateau', 'le', 'bateau'],
        ['voilier', 'le', 'voilier'],
        ['fusee', 'la', 'fusée'],
        ['tracteur', 'le', 'tracteur'],
        ['pelleteuse', 'la', 'pelleteuse'],
        ['camion-de-pompiers', 'le', 'camion de pompiers'],
        ['voiture-de-police', 'la', 'voiture de police'],
        ['ambulance', "l'", 'ambulance'],
        ['sous-marin', 'le', 'sous-marin'],
        ['montgolfiere', 'la', 'montgolfière'],
        ['trottinette', 'la', 'trottinette'],
        ['skateboard', 'le', 'skateboard'],
      ],
    },
    {
      id: 'maison',
      title: 'À la maison',
      cover: 'tasse',
      items: [
        ['table', 'la', 'table'],
        ['chaise', 'la', 'chaise'],
        ['lit', 'le', 'lit'],
        ['canape', 'le', 'canapé'],
        ['lampe', 'la', 'lampe'],
        ['porte', 'la', 'porte'],
        ['fenetre', 'la', 'fenêtre'],
        ['horloge', "l'", 'horloge'],
        ['livre', 'le', 'livre'],
        ['television', 'la', 'télévision'],
        ['telephone', 'le', 'téléphone'],
        ['cle', 'la', 'clé'],
        ['tasse', 'la', 'tasse'],
        ['assiette', "l'", 'assiette'],
        ['verre', 'le', 'verre'],
        ['cuillere', 'la', 'cuillère'],
        ['fourchette', 'la', 'fourchette'],
        ['brosse-a-dents', 'la', 'brosse à dents'],
        ['savon', 'le', 'savon'],
        ['baignoire', 'la', 'baignoire'],
      ],
    },
    {
      id: 'vetements',
      title: 'Les vêtements',
      cover: 'bonnet',
      items: [
        ['tee-shirt', 'le', 'tee-shirt'],
        ['pantalon', 'le', 'pantalon'],
        ['robe', 'la', 'robe'],
        ['jupe', 'la', 'jupe'],
        ['pull', 'le', 'pull'],
        ['manteau', 'le', 'manteau'],
        ['pyjama', 'le', 'pyjama'],
        ['chaussette', 'la', 'chaussette'],
        ['chaussure', 'la', 'chaussure'],
        ['botte', 'la', 'botte'],
        ['chapeau', 'le', 'chapeau'],
        ['bonnet', 'le', 'bonnet'],
        ['echarpe', "l'", 'écharpe'],
        ['gants', 'les', 'gants'],
        ['maillot-de-bain', 'le', 'maillot de bain'],
        ['casquette', 'la', 'casquette'],
      ],
    },
    {
      id: 'nature',
      title: 'La nature',
      cover: 'arc-en-ciel',
      items: [
        ['soleil', 'le', 'soleil'],
        ['lune', 'la', 'lune'],
        ['etoile', "l'", 'étoile'],
        ['nuage', 'le', 'nuage'],
        ['pluie', 'la', 'pluie'],
        ['arc-en-ciel', "l'", 'arc-en-ciel'],
        ['bonhomme-de-neige', 'le', 'bonhomme de neige'],
        ['eclair', "l'", 'éclair'],
        ['arbre', "l'", 'arbre'],
        ['fleur', 'la', 'fleur'],
        ['feuille', 'la', 'feuille'],
        ['sapin', 'le', 'sapin'],
        ['montagne', 'la', 'montagne'],
        ['cactus', 'le', 'cactus'],
        ['tournesol', 'le', 'tournesol'],
        ['palmier', 'le', 'palmier'],
        ['volcan', 'le', 'volcan'],
        ['flocon-de-neige', 'le', 'flocon de neige'],
      ],
    },
    {
      id: 'miam',
      title: 'Miam miam !',
      cover: 'glace',
      items: [
        ['pain', 'le', 'pain'],
        ['croissant', 'le', 'croissant'],
        ['fromage', 'le', 'fromage'],
        ['oeuf', "l'", 'œuf'],
        ['lait', 'le', 'lait'],
        ['gateau', 'le', 'gâteau'],
        ['biscuit', 'le', 'biscuit'],
        ['glace', 'la', 'glace'],
        ['bonbon', 'le', 'bonbon'],
        ['chocolat', 'le', 'chocolat'],
        ['pizza', 'la', 'pizza'],
        ['pates', 'les', 'pâtes'],
        ['soupe', 'la', 'soupe'],
        ['yaourt', 'le', 'yaourt'],
        ['confiture', 'la', 'confiture'],
        ['jus-dorange', 'le', "jus d'orange"],
        ['crepe', 'la', 'crêpe'],
        ['sandwich', 'le', 'sandwich'],
      ],
    },
    {
      id: 'jouets',
      title: 'Les jouets',
      cover: 'nounours',
      items: [
        ['ballon', 'le', 'ballon'],
        ['poupee', 'la', 'poupée'],
        ['nounours', 'le', 'nounours'],
        ['puzzle', 'le', 'puzzle'],
        ['cubes', 'les', 'cubes'],
        ['toupie', 'la', 'toupie'],
        ['tambour', 'le', 'tambour'],
        ['guitare', 'la', 'guitare'],
        ['xylophone', 'le', 'xylophone'],
        ['trompette', 'la', 'trompette'],
        ['robot', 'le', 'robot'],
        ['cerf-volant', 'le', 'cerf-volant'],
        ['balancoire', 'la', 'balançoire'],
        ['toboggan', 'le', 'toboggan'],
        ['seau', 'le', 'seau'],
        ['crayons', 'les', 'crayons'],
      ],
    },
  ],
};
